### ISSUE TITLE
Launch app maximized on first load

### ISSUE THREAD

**Issue by onetrev** [ZeroX-DG/SnippetStore#19]
Just another super small thing, but I noticed that on first load SnippetStore doesn't launch fully maximized. I know other Electron apps used to have that issue, but don't seem to any more. Would this part of the API fix that? https://electronjs.org/docs/api/browser-window#winmaximize

PS, thank you for the big donation credit. I really appreciate your work on this app though, especially the VS Code integration, which is key! All around an awesome productivity tool!

**Comment by ZeroX-DG** [comment]
Thanks, @onetrev I'll fix it soon :+1:

**Comment by ZeroX-DG** [comment]
Fixed in the latest release:
https://github.com/ZeroX-DG/SnippetStore/releases/tag/v0.2.10

**Comment by onetrev** [comment]
Hello! Sorry to report that for me at least the app still doesn't open full screen on first load. Anything I can troubleshoot to assist?

PS, hopefully you can add auto-update or definitely at least a notice when a new version is out. Lots of people probably missing out on the new features and bug fixes being added.

**Comment by ZeroX-DG** [comment]
Thanks, @onetrev somehow the bug re-appear again :cry: I'll implement something to notify users when there's a new version. I'm still learning how to create auto-update :smile:
