### ISSUE TITLE
Snippets Store Showing Blank on VSCode

### ISSUE THREAD

**Issue by vurch** [ZeroX-DG/SnippetStore#49]
Transfer Selection to Snippets Store is Showing Blank on version 0.2.11.

**Comment by ZeroX-DG** [comment]
Thank you for reporting, I'll fix this bug asap.

**Comment by sumaliqinghua** [comment]
I find this bug too.This bug didnt appear on 0.2.10

**Comment by EdvardM** [comment]
Confirmed. Selecting text and "transfer selection to snippet store" at has always caused me to make snippet store show just blank page.

**Comment by ZeroX-DG** [comment]
Sorry for the delay. I'll release the new version tomorrow and it will fix this issue. Sorry for the inconvenience

**Comment by ZeroX-DG** [comment]
Can you guys confirm that the bug has been fixed in the pre-release?
https://github.com/ZeroX-DG/SnippetStore/releases/tag/v0.2.12

**Comment by luke-techspra** [comment]
This is still an issue (v 0.2.11). Selecting text and "transfer selection to snippet store" at has always caused me to make snippet store show just blank page.
